### ISSUE TITLE
include/exclude project in a list

### ISSUE THREAD

**Issue by shemerey** [mehcode/atom-project-plus#10]
I would like to implement include/exclude functionality, so your opinion is really important.

General idea is implementing some kind of `.gitignore` functionality. It can be setting in a plugin itself or config file in `Atom` config dir. 

Main goal is to add basic filtering functionality `include/exclude` and clean up project list

**Comment by mehcode** [comment]
Hmm.. Sort of a whitelist / blacklist type deal? That makes sense. I could see a glob list for include/exclude in the configuration of this package. Definitely like the idea. I work primarily out of a `~/Workspace` directory (because reasons and old habits die hard). It could be nice to only show projects that are in that directory.

![image](https://cloud.githubusercontent.com/assets/753919/13351562/511f43ba-dc3c-11e5-8bba-fdd13d4076c6.png)

![image](https://cloud.githubusercontent.com/assets/753919/13351593/a01ef71c-dc3c-11e5-95e4-928bc26f464a.png)

Poked around in atom for how similar configuration is done already. I'm liking the names `Folder Whitelist` and `Folder Blacklist` the best at the moment. I'd like to expand os variables in the patterns (I'd want to be able to set `~/Workspace` as the Whitelist). I found https://github.com/sindresorhus/untildify from a quick search.

**Comment by shemerey** [comment]
@mehcode thx, will do it

**Comment by mehcode** [comment]
Thanks for the addition. I made some small adjustments to it; let me know what you think of it.
