### ISSUE TITLE
Projects found from inside an already found project

### ISSUE THREAD

**Issue by hultberg** [mehcode/atom-project-plus#16]
Hello

After testing the package out I found that when viewing the projects found it looks recursively(?). And if I have a folder with the same name inside an project folder it shows up multiple times, example:

```
Include: /home/user/workspace/

* project1
/home/user/workspace/project1

* project1
/home/user/workspace/project1/include/project1
```

**Comment by shemerey** [comment]
@hultberg it's related with https://github.com/mehcode/atom-project-plus/issues/10 and https://github.com/mehcode/atom-project-plus/pull/12 and last changes in path resolving, I am woking on a new example to show for @mehcode Will finish it soon

**Comment by mehcode** [comment]
I don't think this is that @shemerey 

---

> And if I have a folder with the same name inside an project folder it shows up multiple times, example

There is only one reason why a project would show up "multiple times". It's because you have the same path in more than one "state". In other words, at some point in time (before you installed this package) you opened up `/home/user/workspace/project1` then added `/home/user/workspace/project1/include/project1` as another folder to that project. That will result in two "states" (and thus two entries that appear identical).

I'm still thinking of the best way to solve this. https://github.com/mehcode/atom-project-plus/issues/8 talks about it some more.

Some options:
- Ignore it. Projects are sorted by MRU so that helps.
- Add https://github.com/mehcode/atom-project-plus/issues/9 and explicitly remove the project you don't want to show (probably the one with just one path and not two).
- Listen to project path add/remove and auto-archive ( #9 ) the previous project. Picture atom's understanding of projects as a SQL table and the primary key a list of project paths. Changing the active paths makes a new entry in the table. We could listen for this and auto-hide the old one. 

I've done the first one to help mitigate the problem (it helps for me at least). The second and third are progressively more involved but will solve it completely. Unfortunately the third would only apply to new projects made after installing this package.

---

Yet another option (if its really bugging you and you just want to use this project for switching now) -- just remove all your existing state with `rm -rf ~/.atom/storage` (will not remove packages or config). You'll really feel the lack of #5 however.

**Comment by mehcode** [comment]
Wait.. after re reading your question it looks like I misun

**Comment by mehcode** [comment]
Wait.. after re reading your question it looks like I misunderstood. What you're seeing just means that at one point in time you've opened up that inner folder with atom. #9 is your friend then. That's pretty simple and will get done next.

**Comment by mehcode** [comment]
@hultberg Can you update to the latest version of project plus (0.7.0) and let me know if the recent changes fix things enough for you? I'm going to close this for now.
