### ISSUE TITLE
Disabling auto discover not working.

### ISSUE THREAD

**Issue by VZout** [mehcode/atom-project-plus#41]
Disabling Auto Discover Projects does not work. I still get these to projects which are not located in my projects.cson http://i.imgur.com/lZjesSR.png

**Comment by mehcode** [comment]
I can't reproduce this. Can you make sure you're on v0.8.2 and then show me your project plus config and your projects.cson file. I tried adding those paths so that discover would find them but didn't add them to projects.cson -- they do not show up in the finder.

Also.. what Atom version are you using? And does upgrading to 1.7.x help (it's stable now)?

**Comment by markmcintyre** [comment]
I'm having the same issue. I disabled auto discovery, but projects that aren't in my projects.cson are appearing. I first encountered this issue when I renamed a project folder to another. The old name continues to appear.

**Comment by marfarma** [comment]
Newly installed and my projects.cson contains only `{}`  -- setting autodiscover to off has no effect.

Searching the repo shows this in the changelog: 

```
:tada: Support `projects.cson` from [project manager](https://github.com/danielbrodin/atom-project-manager) as `FileProvider`
```

Suggests that projects.cson needs to be created / maintained by another plugin, atom project manager -- or manually.  If so, documentation needs to be improved to say so.

**Comment by krisis-nl** [comment]
It seems that added project folders in the past count as 'saved projects'. You can clear the history by deleting the editor entries in the ~/.atom/storage folder. This is what worked for me at least.

**Comment by markmcintyre** [comment]
Clearing out ~/.atom/storage worked for me as well.
