### ISSUE TITLE
Project Plus: Toggle Project Finder is populated with useless entries

### ISSUE THREAD

**Issue by GrantSP** [mehcode/atom-project-plus#63]
When i call the Finder with <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>P</kbd> the resultant list is populated with many entries that I can't remove.
**projects.cson** contains only those projects that I have explicitly added and I can't see where these other entries are stored.

**Comment by willdawsonme** [comment]
@GrantSP That is most likely due to Auto Discover, which you can turn off in the Project Plus settings! You should still be able to remove the discovered entries though if you'd like to keep Auto Discover on; there's an entry in the command palette (`Project Plus: Remove`) that will let you do so. Does that answer your question?

**Comment by GrantSP** [comment]
Yes, that was it. Auto-discover is now disabled and the list of projects is showing only those that I explicitly save.
Thank you. That feature must override the Remove function because I simply could not Remove those projects using that command, they always reappeared. 
I think this can be closed now. Thank you again.

**Comment by willdawsonme** [comment]
@GrantSP Good to hear! Removing projects that were discovered should work and does for me on the latest Atom (1.9.8). If it keeps happening, feel free to open another issue and we'll have a look.
