### ISSUE TITLE
cannot work on Atom 1.17.0 beta

### ISSUE THREAD

**Issue by zzjin** [mehcode/atom-project-plus#93]
RT
 can switch to new project but tree view was cleared.

**Comment by shemerey** [comment]
same for me

**Comment by xream** [comment]
This is caused by atom-project-util.

I made a new package for 1.17.0+: https://atom.io/packages/project-neue

**Comment by vinyll** [comment]
Same issue here with Atom 1.17.
I've installed @xream's project-neue but it does not solve anything in my case.

Temporary solution is to move to the _project manager_ popular package in the meantime.

**Comment by mehcode** [comment]
@xream Would you mind sending a PR to [atom-project-util](https://github.com/mehcode/atom-project-util) instead?  https://github.com/danielbrodin/atom-project-manager uses that as well for its project switching so if there is an issue with 1.17+ I'd be awesome to have the fix there.

---

@vinyll Since you seem to feel that is a temporary solution would you mind chiming in on #95 as to why?

**Comment by xream** [comment]
@mehcode to to honest, I don't have the time. I use this api `atom.restoreStateIntoThisEnvironment(state)` in 1.17+.

**Comment by vinyll** [comment]
FYI I have the same issue with Project Manager when opening in the same window; the folders tree is empty.

**Comment by mehcode** [comment]
Fixed and released as v1.0
